version: "3"
services:
  client-web:
    image: node:12.14.1
    user: "node"
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - ./client-web:/home/node/app
    environment:
      - NODE_ENV=development
    command: "npm start"

networks:
  reactchallenge2:
    driver: bridge
