version: "3"
services:
  client-web:
    image: node:12.14.1
    user: "node"
    ports:
      - ${HOST_NODE_PORT}:${CONTAINER_NODE_PORT}
    working_dir: /home/node/app
    volumes:
      - ./client-web:/home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - NPM_CONFIG_LOGLEVEL=${NPM_CONFIG_LOGLEVEL}
    command: bash -c "
        npm install
        && npm rebuild node-sass
        && npm start
      "

networks:
  reactchallenge2:
    driver: bridge
