version: "3"
services:
  ## API
  api:
    image: adebayo98/apache2_for_reactchallenge2
    user: "root"
    working_dir: /var/www/html
    networks:
      - reactchallenge2
    volumes:
      - ./api:/var/www/html
    ports:
      - ${HOST_APACHE_PORT}:${CONTAINER_APACHE_PORT}
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DEBIAN_FRONTEND=noninteractive

  ## CLIENT WEB
  client-web:
    image: node:12.14.1
    user: "node"
    working_dir: /home/node/app
    networks:
      - reactchallenge2
    ports:
      - ${HOST_NODE_PORT}:${CONTAINER_NODE_PORT}
    volumes:
      - ./client-web:/home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - NPM_CONFIG_LOGLEVEL=${NPM_CONFIG_LOGLEVEL}
    command: bash -c ${CONTAINER_NODE_CONTEXT_CMD}

  ## CLIENT MOB

networks:
  reactchallenge2:
    driver: bridge
