<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpJuxOs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpJuxOs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWpJuxOs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWpJuxOs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWpJuxOs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WpJuxOs',
    'container.build_id' => '65b610b0',
    'container.build_time' => 1580225070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpJuxOs');
